import * as LucideIcons from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const FALLBACK_ICON = LucideIcons.CircleHelpIcon as LucideIcon;

function icon(name: string) {
  return (
    (LucideIcons as unknown as Record<string, LucideIcon | undefined>)[name] ??
    FALLBACK_ICON
  );
}

export const ICON_REGISTRY = {
  graduation_cap: icon("GraduationCapIcon"),
  briefcase: icon("BriefcaseIcon"),
  plane: icon("PlaneIcon"),
  users: icon("UsersIcon"),
  building: icon("BuildingIcon"),
  building_2: icon("Building2Icon"),
  book_open: icon("BookOpenIcon"),
  globe: icon("GlobeIcon"),
  map_pin: icon("MapPinIcon"),
  phone: icon("PhoneIcon"),
  mail: icon("MailIcon"),
  clock: icon("ClockIcon"),
  message_circle: icon("MessageCircleIcon"),
  file_text: icon("FileTextIcon"),
  download: icon("DownloadIcon"),
  shield_check: icon("ShieldCheckIcon"),
  award: icon("AwardIcon"),
  handshake: icon("HandshakeIcon"),
  factory: icon("FactoryIcon"),
  hard_hat: icon("HardHatIcon"),
  sprout: icon("SproutIcon"),
  heart_pulse: icon("HeartPulseIcon"),
  utensils: icon("UtensilsIcon"),
  hotel: icon("HotelIcon"),
  wrench: icon("WrenchIcon"),
  languages: icon("LanguagesIcon"),
  user_check: icon("UserCheckIcon"),
  network: icon("NetworkIcon"),
  newspaper: icon("NewspaperIcon"),
  calendar_days: icon("CalendarDaysIcon"),
  star: icon("StarIcon"),
  circle_check: icon("CircleCheckIcon"),
  check: icon("CheckIcon"),
  heart: icon("HeartIcon"),
  book: icon("BookOpenIcon"),
  home: icon("HomeIcon"),
  map: icon("MapIcon"),
  target: icon("TargetIcon"),
  rocket: icon("RocketIcon"),
  landmark: icon("LandmarkIcon"),
  school: icon("SchoolIcon"),
  university: icon("UniversityIcon"),
  notebook: icon("NotebookIcon"),
  notebook_pen: icon("NotebookPenIcon"),
  notebook_tabs: icon("NotebookTabsIcon"),
  book_marked: icon("BookMarkedIcon"),
  book_open_check: icon("BookOpenCheckIcon"),
  book_open_text: icon("BookOpenTextIcon"),
  library: icon("LibraryIcon"),
  library_big: icon("LibraryBigIcon"),
  presentation: icon("PresentationIcon"),
  screen_share: icon("ScreenShareIcon"),
  lectern: icon("LecternIcon"),
  clipboard_check: icon("ClipboardCheckIcon"),
  clipboard_list: icon("ClipboardListIcon"),
  clipboard_pen_line: icon("ClipboardPenLineIcon"),
  pencil: icon("PencilIcon"),
  pen_line: icon("PenLineIcon"),
  list_checks: icon("ListChecksIcon"),
  badge_check: icon("BadgeCheckIcon"),
  medal: icon("MedalIcon"),
  trophy: icon("TrophyIcon"),
  sparkles: icon("SparklesIcon"),
  brain: icon("BrainIcon"),
  lightbulb: icon("LightbulbIcon"),
  ship: icon("ShipIcon"),
  train: icon("TrainIcon"),
  bus: icon("BusIcon"),
  car: icon("CarIcon"),
  route: icon("RouteIcon"),
  navigation: icon("NavigationIcon"),
  compass: icon("CompassIcon"),
  map_pinned: icon("MapPinnedIcon"),
  map_pin_check: icon("MapPinCheckIcon"),
  flag: icon("FlagIcon"),
  flag_triangle_right: icon("FlagTriangleRightIcon"),
  ticket_check: icon("TicketCheckIcon"),
  id_card: icon("IdCardIcon"),
  scan_face: icon("ScanFaceIcon"),
  japanese_yen: icon("JapaneseYenIcon"),
  hammer: icon("HammerIcon"),
  anvil: icon("AnvilIcon"),
  pickaxe: icon("PickaxeIcon"),
  drill: icon("DrillIcon"),
  construction: icon("ConstructionIcon"),
  warehouse: icon("WarehouseIcon"),
  package: icon("PackageIcon"),
  truck: icon("TruckIcon"),
  forklift: icon("ForkliftIcon"),
  tractor: icon("TractorIcon"),
  wheat: icon("WheatIcon"),
  fish: icon("FishIcon"),
  beef: icon("BeefIcon"),
  chef_hat: icon("ChefHatIcon"),
  cooking_pot: icon("CookingPotIcon"),
  utensils_crossed: icon("UtensilsCrossedIcon"),
  bed: icon("BedIcon"),
  bed_double: icon("BedDoubleIcon"),
  stethoscope: icon("StethoscopeIcon"),
  hospital: icon("HospitalIcon"),
  syringe: icon("SyringeIcon"),
  pill: icon("PillIcon"),
  heart_handshake: icon("HeartHandshakeIcon"),
  hand_heart: icon("HandHeartIcon"),
  hand_helping: icon("HandHelpingIcon"),
  shovel: icon("ShovelIcon"),
  briefcase_business: icon("BriefcaseBusinessIcon"),
  contact: icon("ContactIcon"),
  contact_round: icon("ContactRoundIcon"),
  user_round_check: icon("UserRoundCheckIcon"),
  user_round_plus: icon("UserRoundPlusIcon"),
  users_round: icon("UsersRoundIcon"),
  user_search: icon("UserSearchIcon"),
  file_check: icon("FileCheckIcon"),
  file_badge: icon("FileBadgeIcon"),
  file_box: icon("FileBoxIcon"),
  files: icon("FilesIcon"),
  folder_check: icon("FolderCheckIcon"),
  folder_open: icon("FolderOpenIcon"),
  archive: icon("ArchiveIcon"),
  paperclip: icon("PaperclipIcon"),
  scroll_text: icon("ScrollTextIcon"),
  signature: icon("SignatureIcon"),
  stamp: icon("StampIcon"),
  shield: icon("ShieldIcon"),
  shield_alert: icon("ShieldAlertIcon"),
  shield_user: icon("ShieldUserIcon"),
  lock_keyhole: icon("LockKeyholeIcon"),
  key_round: icon("KeyRoundIcon"),
  fingerprint: icon("FingerprintIcon"),
  scan_line: icon("ScanLineIcon"),
  circle_alert: icon("CircleAlertIcon"),
  circle_x: icon("CircleXIcon"),
  timer: icon("TimerIcon"),
  timer_reset: icon("TimerResetIcon"),
  hourglass: icon("HourglassIcon"),
  calendar_check: icon("CalendarCheckIcon"),
  calendar_clock: icon("CalendarClockIcon"),
  calendar_range: icon("CalendarRangeIcon"),
  info: icon("InfoIcon"),
} satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof ICON_REGISTRY;

export const ICON_OPTIONS = Object.keys(ICON_REGISTRY).map((key) => ({
  key,
  label: key
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" "),
}));

export function getIconComponent(iconKey: string | null | undefined) {
  if (!iconKey) {
    return FALLBACK_ICON;
  }

  return ICON_REGISTRY[iconKey as IconKey] ?? FALLBACK_ICON;
}
